[package]
name = "local-set-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.24"
once_cell = "1.14.0"
tokio = { version = "1.21.0", features = ["full"] }
